filename: mocks_test.go
log-level: error
pkgname: '{{.SrcPackageName}}_test'
packages:
  github.com/davidsbond/keeper/internal/server/api:
    config:
      all: true
  github.com/davidsbond/keeper/internal/server/service:
    config:
      all: true
