[http]
bind = "0.0.0.0:8080"

[database]
path = ".data"
ttl = "1h"
master_key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

[jwt]
issuer = "dev"
audience = "dev"
ttl = "30m"
signing_key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
