// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"github.com/davidsbond/keeper/internal/server/database"
	"github.com/davidsbond/keeper/internal/server/token"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryProvider creates a new instance of MockRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProvider[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProvider[T] {
	mock := &MockRepositoryProvider[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type MockRepositoryProvider[T any] struct {
	mock.Mock
}

type MockRepositoryProvider_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProvider[T]) EXPECT() *MockRepositoryProvider_Expecter[T] {
	return &MockRepositoryProvider_Expecter[T]{mock: &_m.Mock}
}

// For provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider[T]) For(uUID uuid.UUID) (T, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for For")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryProvider_For_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'For'
type MockRepositoryProvider_For_Call[T any] struct {
	*mock.Call
}

// For is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockRepositoryProvider_Expecter[T]) For(uUID interface{}) *MockRepositoryProvider_For_Call[T] {
	return &MockRepositoryProvider_For_Call[T]{Call: _e.mock.On("For", uUID)}
}

func (_c *MockRepositoryProvider_For_Call[T]) Run(run func(uUID uuid.UUID)) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryProvider_For_Call[T]) Return(v T, err error) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepositoryProvider_For_Call[T]) RunAndReturn(run func(uUID uuid.UUID) (T, error)) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabaseManager creates a new instance of MockDatabaseManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseManager {
	mock := &MockDatabaseManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseManager is an autogenerated mock type for the DatabaseManager type
type MockDatabaseManager struct {
	mock.Mock
}

type MockDatabaseManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseManager) EXPECT() *MockDatabaseManager_Expecter {
	return &MockDatabaseManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Create(accountID uuid.UUID, key []byte) error {
	ret := _mock.Called(accountID, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []byte) error); ok {
		r0 = returnFunc(accountID, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDatabaseManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - accountID uuid.UUID
//   - key []byte
func (_e *MockDatabaseManager_Expecter) Create(accountID interface{}, key interface{}) *MockDatabaseManager_Create_Call {
	return &MockDatabaseManager_Create_Call{Call: _e.mock.On("Create", accountID, key)}
}

func (_c *MockDatabaseManager_Create_Call) Run(run func(accountID uuid.UUID, key []byte)) *MockDatabaseManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Create_Call) Return(err error) *MockDatabaseManager_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Create_Call) RunAndReturn(run func(accountID uuid.UUID, key []byte) error) *MockDatabaseManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Delete(accountID uuid.UUID) error {
	ret := _mock.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDatabaseManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - accountID uuid.UUID
func (_e *MockDatabaseManager_Expecter) Delete(accountID interface{}) *MockDatabaseManager_Delete_Call {
	return &MockDatabaseManager_Delete_Call{Call: _e.mock.On("Delete", accountID)}
}

func (_c *MockDatabaseManager_Delete_Call) Run(run func(accountID uuid.UUID)) *MockDatabaseManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Delete_Call) Return(err error) *MockDatabaseManager_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Delete_Call) RunAndReturn(run func(accountID uuid.UUID) error) *MockDatabaseManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Lock(accountID uuid.UUID) error {
	ret := _mock.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockDatabaseManager_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - accountID uuid.UUID
func (_e *MockDatabaseManager_Expecter) Lock(accountID interface{}) *MockDatabaseManager_Lock_Call {
	return &MockDatabaseManager_Lock_Call{Call: _e.mock.On("Lock", accountID)}
}

func (_c *MockDatabaseManager_Lock_Call) Run(run func(accountID uuid.UUID)) *MockDatabaseManager_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Lock_Call) Return(err error) *MockDatabaseManager_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Lock_Call) RunAndReturn(run func(accountID uuid.UUID) error) *MockDatabaseManager_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// RotateKey provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) RotateKey(accountID uuid.UUID, oldKey []byte, newKey []byte) error {
	ret := _mock.Called(accountID, oldKey, newKey)

	if len(ret) == 0 {
		panic("no return value specified for RotateKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []byte, []byte) error); ok {
		r0 = returnFunc(accountID, oldKey, newKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_RotateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateKey'
type MockDatabaseManager_RotateKey_Call struct {
	*mock.Call
}

// RotateKey is a helper method to define mock.On call
//   - accountID uuid.UUID
//   - oldKey []byte
//   - newKey []byte
func (_e *MockDatabaseManager_Expecter) RotateKey(accountID interface{}, oldKey interface{}, newKey interface{}) *MockDatabaseManager_RotateKey_Call {
	return &MockDatabaseManager_RotateKey_Call{Call: _e.mock.On("RotateKey", accountID, oldKey, newKey)}
}

func (_c *MockDatabaseManager_RotateKey_Call) Run(run func(accountID uuid.UUID, oldKey []byte, newKey []byte)) *MockDatabaseManager_RotateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_RotateKey_Call) Return(err error) *MockDatabaseManager_RotateKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_RotateKey_Call) RunAndReturn(run func(accountID uuid.UUID, oldKey []byte, newKey []byte) error) *MockDatabaseManager_RotateKey_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Unlock(accountID uuid.UUID, key []byte) error {
	ret := _mock.Called(accountID, key)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []byte) error); ok {
		r0 = returnFunc(accountID, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockDatabaseManager_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - accountID uuid.UUID
//   - key []byte
func (_e *MockDatabaseManager_Expecter) Unlock(accountID interface{}, key interface{}) *MockDatabaseManager_Unlock_Call {
	return &MockDatabaseManager_Unlock_Call{Call: _e.mock.On("Unlock", accountID, key)}
}

func (_c *MockDatabaseManager_Unlock_Call) Run(run func(accountID uuid.UUID, key []byte)) *MockDatabaseManager_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Unlock_Call) Return(err error) *MockDatabaseManager_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Unlock_Call) RunAndReturn(run func(accountID uuid.UUID, key []byte) error) *MockDatabaseManager_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Create(account database.Account) error {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Account) error); ok {
		r0 = returnFunc(account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account database.Account
func (_e *MockAccountRepository_Expecter) Create(account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(account database.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Account
		if args[0] != nil {
			arg0 = args[0].(database.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(err error) *MockAccountRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(account database.Account) error) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Delete(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockAccountRepository_Expecter) Delete(uUID interface{}) *MockAccountRepository_Delete_Call {
	return &MockAccountRepository_Delete_Call{Call: _e.mock.On("Delete", uUID)}
}

func (_c *MockAccountRepository_Delete_Call) Run(run func(uUID uuid.UUID)) *MockAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Delete_Call) Return(err error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Delete_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByEmail(s string) (database.Account, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 database.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (database.Account, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) database.Account); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(database.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockAccountRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - s string
func (_e *MockAccountRepository_Expecter) FindByEmail(s interface{}) *MockAccountRepository_FindByEmail_Call {
	return &MockAccountRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", s)}
}

func (_c *MockAccountRepository_FindByEmail_Call) Run(run func(s string)) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByEmail_Call) Return(account database.Account, err error) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByEmail_Call) RunAndReturn(run func(s string) (database.Account, error)) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByID(uUID uuid.UUID) (database.Account, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 database.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (database.Account, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) database.Account); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(database.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockAccountRepository_Expecter) FindByID(uUID interface{}) *MockAccountRepository_FindByID_Call {
	return &MockAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", uUID)}
}

func (_c *MockAccountRepository_FindByID_Call) Run(run func(uUID uuid.UUID)) *MockAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) Return(account database.Account, err error) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) RunAndReturn(run func(uUID uuid.UUID) (database.Account, error)) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Update(account database.Account) error {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Account) error); ok {
		r0 = returnFunc(account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - account database.Account
func (_e *MockAccountRepository_Expecter) Update(account interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", account)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(account database.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Account
		if args[0] != nil {
			arg0 = args[0].(database.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(err error) *MockAccountRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(account database.Account) error) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) Generate(uUID uuid.UUID) (token.Token, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (token.Token, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) token.Token); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(token.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockTokenGenerator_Expecter) Generate(uUID interface{}) *MockTokenGenerator_Generate_Call {
	return &MockTokenGenerator_Generate_Call{Call: _e.mock.On("Generate", uUID)}
}

func (_c *MockTokenGenerator_Generate_Call) Run(run func(uUID uuid.UUID)) *MockTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) Return(token1 token.Token, err error) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) RunAndReturn(run func(uUID uuid.UUID) (token.Token, error)) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCardRepository creates a new instance of MockCardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardRepository {
	mock := &MockCardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCardRepository is an autogenerated mock type for the CardRepository type
type MockCardRepository struct {
	mock.Mock
}

type MockCardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardRepository) EXPECT() *MockCardRepository_Expecter {
	return &MockCardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCardRepository
func (_mock *MockCardRepository) Create(card database.Card) error {
	ret := _mock.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Card) error); ok {
		r0 = returnFunc(card)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - card database.Card
func (_e *MockCardRepository_Expecter) Create(card interface{}) *MockCardRepository_Create_Call {
	return &MockCardRepository_Create_Call{Call: _e.mock.On("Create", card)}
}

func (_c *MockCardRepository_Create_Call) Run(run func(card database.Card)) *MockCardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Card
		if args[0] != nil {
			arg0 = args[0].(database.Card)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardRepository_Create_Call) Return(err error) *MockCardRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCardRepository_Create_Call) RunAndReturn(run func(card database.Card) error) *MockCardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCardRepository
func (_mock *MockCardRepository) Delete(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockCardRepository_Expecter) Delete(uUID interface{}) *MockCardRepository_Delete_Call {
	return &MockCardRepository_Delete_Call{Call: _e.mock.On("Delete", uUID)}
}

func (_c *MockCardRepository_Delete_Call) Run(run func(uUID uuid.UUID)) *MockCardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardRepository_Delete_Call) Return(err error) *MockCardRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCardRepository_Delete_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockCardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCardRepository
func (_mock *MockCardRepository) Get(uUID uuid.UUID) (database.Card, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (database.Card, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) database.Card); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(database.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCardRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockCardRepository_Expecter) Get(uUID interface{}) *MockCardRepository_Get_Call {
	return &MockCardRepository_Get_Call{Call: _e.mock.On("Get", uUID)}
}

func (_c *MockCardRepository_Get_Call) Run(run func(uUID uuid.UUID)) *MockCardRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardRepository_Get_Call) Return(card database.Card, err error) *MockCardRepository_Get_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *MockCardRepository_Get_Call) RunAndReturn(run func(uUID uuid.UUID) (database.Card, error)) *MockCardRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCardRepository
func (_mock *MockCardRepository) List() ([]database.Card, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Card, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Card); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockCardRepository_Expecter) List() *MockCardRepository_List_Call {
	return &MockCardRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockCardRepository_List_Call) Run(run func()) *MockCardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCardRepository_List_Call) Return(cards []database.Card, err error) *MockCardRepository_List_Call {
	_c.Call.Return(cards, err)
	return _c
}

func (_c *MockCardRepository_List_Call) RunAndReturn(run func() ([]database.Card, error)) *MockCardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginRepository creates a new instance of MockLoginRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginRepository {
	mock := &MockLoginRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginRepository is an autogenerated mock type for the LoginRepository type
type MockLoginRepository struct {
	mock.Mock
}

type MockLoginRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginRepository) EXPECT() *MockLoginRepository_Expecter {
	return &MockLoginRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) Create(login database.Login) error {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Login) error); ok {
		r0 = returnFunc(login)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - login database.Login
func (_e *MockLoginRepository_Expecter) Create(login interface{}) *MockLoginRepository_Create_Call {
	return &MockLoginRepository_Create_Call{Call: _e.mock.On("Create", login)}
}

func (_c *MockLoginRepository_Create_Call) Run(run func(login database.Login)) *MockLoginRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Login
		if args[0] != nil {
			arg0 = args[0].(database.Login)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginRepository_Create_Call) Return(err error) *MockLoginRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRepository_Create_Call) RunAndReturn(run func(login database.Login) error) *MockLoginRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) Delete(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLoginRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockLoginRepository_Expecter) Delete(uUID interface{}) *MockLoginRepository_Delete_Call {
	return &MockLoginRepository_Delete_Call{Call: _e.mock.On("Delete", uUID)}
}

func (_c *MockLoginRepository_Delete_Call) Run(run func(uUID uuid.UUID)) *MockLoginRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginRepository_Delete_Call) Return(err error) *MockLoginRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRepository_Delete_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockLoginRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) Get(uUID uuid.UUID) (database.Login, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (database.Login, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) database.Login); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(database.Login)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLoginRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockLoginRepository_Expecter) Get(uUID interface{}) *MockLoginRepository_Get_Call {
	return &MockLoginRepository_Get_Call{Call: _e.mock.On("Get", uUID)}
}

func (_c *MockLoginRepository_Get_Call) Run(run func(uUID uuid.UUID)) *MockLoginRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginRepository_Get_Call) Return(login database.Login, err error) *MockLoginRepository_Get_Call {
	_c.Call.Return(login, err)
	return _c
}

func (_c *MockLoginRepository_Get_Call) RunAndReturn(run func(uUID uuid.UUID) (database.Login, error)) *MockLoginRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) List() ([]database.Login, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Login, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Login); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Login)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLoginRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockLoginRepository_Expecter) List() *MockLoginRepository_List_Call {
	return &MockLoginRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockLoginRepository_List_Call) Run(run func()) *MockLoginRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoginRepository_List_Call) Return(logins []database.Login, err error) *MockLoginRepository_List_Call {
	_c.Call.Return(logins, err)
	return _c
}

func (_c *MockLoginRepository_List_Call) RunAndReturn(run func() ([]database.Login, error)) *MockLoginRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoteRepository creates a new instance of MockNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteRepository {
	mock := &MockNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteRepository is an autogenerated mock type for the NoteRepository type
type MockNoteRepository struct {
	mock.Mock
}

type MockNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteRepository) EXPECT() *MockNoteRepository_Expecter {
	return &MockNoteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Create(note database.Note) error {
	ret := _mock.Called(note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Note) error); ok {
		r0 = returnFunc(note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNoteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - note database.Note
func (_e *MockNoteRepository_Expecter) Create(note interface{}) *MockNoteRepository_Create_Call {
	return &MockNoteRepository_Create_Call{Call: _e.mock.On("Create", note)}
}

func (_c *MockNoteRepository_Create_Call) Run(run func(note database.Note)) *MockNoteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Note
		if args[0] != nil {
			arg0 = args[0].(database.Note)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Create_Call) Return(err error) *MockNoteRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_Create_Call) RunAndReturn(run func(note database.Note) error) *MockNoteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Delete(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNoteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockNoteRepository_Expecter) Delete(uUID interface{}) *MockNoteRepository_Delete_Call {
	return &MockNoteRepository_Delete_Call{Call: _e.mock.On("Delete", uUID)}
}

func (_c *MockNoteRepository_Delete_Call) Run(run func(uUID uuid.UUID)) *MockNoteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Delete_Call) Return(err error) *MockNoteRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteRepository_Delete_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockNoteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) Get(uUID uuid.UUID) (database.Note, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 database.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (database.Note, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) database.Note); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(database.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNoteRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockNoteRepository_Expecter) Get(uUID interface{}) *MockNoteRepository_Get_Call {
	return &MockNoteRepository_Get_Call{Call: _e.mock.On("Get", uUID)}
}

func (_c *MockNoteRepository_Get_Call) Run(run func(uUID uuid.UUID)) *MockNoteRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoteRepository_Get_Call) Return(note database.Note, err error) *MockNoteRepository_Get_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNoteRepository_Get_Call) RunAndReturn(run func(uUID uuid.UUID) (database.Note, error)) *MockNoteRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNoteRepository
func (_mock *MockNoteRepository) List() ([]database.Note, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Note, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Note); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNoteRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockNoteRepository_Expecter) List() *MockNoteRepository_List_Call {
	return &MockNoteRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockNoteRepository_List_Call) Run(run func()) *MockNoteRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoteRepository_List_Call) Return(notes []database.Note, err error) *MockNoteRepository_List_Call {
	_c.Call.Return(notes, err)
	return _c
}

func (_c *MockNoteRepository_List_Call) RunAndReturn(run func() ([]database.Note, error)) *MockNoteRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
