// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"github.com/davidsbond/passwords/internal/server/database"
	"github.com/davidsbond/passwords/internal/server/token"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryProvider creates a new instance of MockRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProvider[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProvider[T] {
	mock := &MockRepositoryProvider[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type MockRepositoryProvider[T any] struct {
	mock.Mock
}

type MockRepositoryProvider_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProvider[T]) EXPECT() *MockRepositoryProvider_Expecter[T] {
	return &MockRepositoryProvider_Expecter[T]{mock: &_m.Mock}
}

// For provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider[T]) For(uUID uuid.UUID) (T, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for For")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryProvider_For_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'For'
type MockRepositoryProvider_For_Call[T any] struct {
	*mock.Call
}

// For is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockRepositoryProvider_Expecter[T]) For(uUID interface{}) *MockRepositoryProvider_For_Call[T] {
	return &MockRepositoryProvider_For_Call[T]{Call: _e.mock.On("For", uUID)}
}

func (_c *MockRepositoryProvider_For_Call[T]) Run(run func(uUID uuid.UUID)) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryProvider_For_Call[T]) Return(v T, err error) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepositoryProvider_For_Call[T]) RunAndReturn(run func(uUID uuid.UUID) (T, error)) *MockRepositoryProvider_For_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabaseManager creates a new instance of MockDatabaseManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseManager {
	mock := &MockDatabaseManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseManager is an autogenerated mock type for the DatabaseManager type
type MockDatabaseManager struct {
	mock.Mock
}

type MockDatabaseManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseManager) EXPECT() *MockDatabaseManager_Expecter {
	return &MockDatabaseManager_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Lock(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockDatabaseManager_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockDatabaseManager_Expecter) Lock(uUID interface{}) *MockDatabaseManager_Lock_Call {
	return &MockDatabaseManager_Lock_Call{Call: _e.mock.On("Lock", uUID)}
}

func (_c *MockDatabaseManager_Lock_Call) Run(run func(uUID uuid.UUID)) *MockDatabaseManager_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Lock_Call) Return(err error) *MockDatabaseManager_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Lock_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockDatabaseManager_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Unlock(uUID uuid.UUID, bytes []byte) error {
	ret := _mock.Called(uUID, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []byte) error); ok {
		r0 = returnFunc(uUID, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockDatabaseManager_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - bytes []byte
func (_e *MockDatabaseManager_Expecter) Unlock(uUID interface{}, bytes interface{}) *MockDatabaseManager_Unlock_Call {
	return &MockDatabaseManager_Unlock_Call{Call: _e.mock.On("Unlock", uUID, bytes)}
}

func (_c *MockDatabaseManager_Unlock_Call) Run(run func(uUID uuid.UUID, bytes []byte)) *MockDatabaseManager_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Unlock_Call) Return(err error) *MockDatabaseManager_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Unlock_Call) RunAndReturn(run func(uUID uuid.UUID, bytes []byte) error) *MockDatabaseManager_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Create(account database.Account) error {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Account) error); ok {
		r0 = returnFunc(account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account database.Account
func (_e *MockAccountRepository_Expecter) Create(account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(account database.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Account
		if args[0] != nil {
			arg0 = args[0].(database.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(err error) *MockAccountRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(account database.Account) error) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) FindByEmail(s string) (database.Account, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 database.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (database.Account, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) database.Account); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(database.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockAccountRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - s string
func (_e *MockAccountRepository_Expecter) FindByEmail(s interface{}) *MockAccountRepository_FindByEmail_Call {
	return &MockAccountRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", s)}
}

func (_c *MockAccountRepository_FindByEmail_Call) Run(run func(s string)) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_FindByEmail_Call) Return(account database.Account, err error) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_FindByEmail_Call) RunAndReturn(run func(s string) (database.Account, error)) *MockAccountRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) Generate(uUID uuid.UUID) (token.Token, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (token.Token, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) token.Token); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(token.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockTokenGenerator_Expecter) Generate(uUID interface{}) *MockTokenGenerator_Generate_Call {
	return &MockTokenGenerator_Generate_Call{Call: _e.mock.On("Generate", uUID)}
}

func (_c *MockTokenGenerator_Generate_Call) Run(run func(uUID uuid.UUID)) *MockTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) Return(token1 token.Token, err error) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) RunAndReturn(run func(uUID uuid.UUID) (token.Token, error)) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginRepository creates a new instance of MockLoginRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginRepository {
	mock := &MockLoginRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginRepository is an autogenerated mock type for the LoginRepository type
type MockLoginRepository struct {
	mock.Mock
}

type MockLoginRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginRepository) EXPECT() *MockLoginRepository_Expecter {
	return &MockLoginRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) Create(login database.Login) error {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.Login) error); ok {
		r0 = returnFunc(login)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - login database.Login
func (_e *MockLoginRepository_Expecter) Create(login interface{}) *MockLoginRepository_Create_Call {
	return &MockLoginRepository_Create_Call{Call: _e.mock.On("Create", login)}
}

func (_c *MockLoginRepository_Create_Call) Run(run func(login database.Login)) *MockLoginRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Login
		if args[0] != nil {
			arg0 = args[0].(database.Login)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginRepository_Create_Call) Return(err error) *MockLoginRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRepository_Create_Call) RunAndReturn(run func(login database.Login) error) *MockLoginRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) Delete(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLoginRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockLoginRepository_Expecter) Delete(uUID interface{}) *MockLoginRepository_Delete_Call {
	return &MockLoginRepository_Delete_Call{Call: _e.mock.On("Delete", uUID)}
}

func (_c *MockLoginRepository_Delete_Call) Run(run func(uUID uuid.UUID)) *MockLoginRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginRepository_Delete_Call) Return(err error) *MockLoginRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRepository_Delete_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockLoginRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) List() ([]database.Login, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Login, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Login); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Login)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLoginRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockLoginRepository_Expecter) List() *MockLoginRepository_List_Call {
	return &MockLoginRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockLoginRepository_List_Call) Run(run func()) *MockLoginRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoginRepository_List_Call) Return(logins []database.Login, err error) *MockLoginRepository_List_Call {
	_c.Call.Return(logins, err)
	return _c
}

func (_c *MockLoginRepository_List_Call) RunAndReturn(run func() ([]database.Login, error)) *MockLoginRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
