// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"github.com/davidsbond/keeper/internal/server/service"
	"github.com/davidsbond/keeper/internal/server/token"
	"github.com/davidsbond/x/filter"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatable creates a new instance of MockValidatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatable {
	mock := &MockValidatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatable is an autogenerated mock type for the Validatable type
type MockValidatable struct {
	mock.Mock
}

type MockValidatable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatable) EXPECT() *MockValidatable_Expecter {
	return &MockValidatable_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidatable
func (_mock *MockValidatable) Validate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidatable_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidatable_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *MockValidatable_Expecter) Validate() *MockValidatable_Validate_Call {
	return &MockValidatable_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *MockValidatable_Validate_Call) Run(run func()) *MockValidatable_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatable_Validate_Call) Return(err error) *MockValidatable_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidatable_Validate_Call) RunAndReturn(run func() error) *MockValidatable_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Create(account service.Account) ([]byte, error) {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(service.Account) ([]byte, error)); ok {
		return returnFunc(account)
	}
	if returnFunc, ok := ret.Get(0).(func(service.Account) []byte); ok {
		r0 = returnFunc(account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(service.Account) error); ok {
		r1 = returnFunc(account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account service.Account
func (_e *MockAccountService_Expecter) Create(account interface{}) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *MockAccountService_Create_Call) Run(run func(account service.Account)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 service.Account
		if args[0] != nil {
			arg0 = args[0].(service.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(bytes []byte, err error) *MockAccountService_Create_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(account service.Account) ([]byte, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(s string, s1 string) (token.Token, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (token.Token, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) token.Token); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(token.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockAuthService_Expecter) Login(s interface{}, s1 interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", s, s1)}
}

func (_c *MockAuthService_Login_Call) Run(run func(s string, s1 string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(token1 token.Token, err error) *MockAuthService_Login_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(s string, s1 string) (token.Token, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockAuthService_Expecter) Logout(uUID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", uUID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(uUID uuid.UUID)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginService creates a new instance of MockLoginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginService {
	mock := &MockLoginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginService is an autogenerated mock type for the LoginService type
type MockLoginService struct {
	mock.Mock
}

type MockLoginService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginService) EXPECT() *MockLoginService_Expecter {
	return &MockLoginService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLoginService
func (_mock *MockLoginService) Create(uUID uuid.UUID, login service.Login) error {
	ret := _mock.Called(uUID, login)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, service.Login) error); ok {
		r0 = returnFunc(uUID, login)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - login service.Login
func (_e *MockLoginService_Expecter) Create(uUID interface{}, login interface{}) *MockLoginService_Create_Call {
	return &MockLoginService_Create_Call{Call: _e.mock.On("Create", uUID, login)}
}

func (_c *MockLoginService_Create_Call) Run(run func(uUID uuid.UUID, login service.Login)) *MockLoginService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 service.Login
		if args[1] != nil {
			arg1 = args[1].(service.Login)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginService_Create_Call) Return(err error) *MockLoginService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginService_Create_Call) RunAndReturn(run func(uUID uuid.UUID, login service.Login) error) *MockLoginService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLoginService
func (_mock *MockLoginService) Delete(uUID uuid.UUID, uUID1 uuid.UUID) error {
	ret := _mock.Called(uUID, uUID1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(uUID, uUID1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLoginService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - uUID1 uuid.UUID
func (_e *MockLoginService_Expecter) Delete(uUID interface{}, uUID1 interface{}) *MockLoginService_Delete_Call {
	return &MockLoginService_Delete_Call{Call: _e.mock.On("Delete", uUID, uUID1)}
}

func (_c *MockLoginService_Delete_Call) Run(run func(uUID uuid.UUID, uUID1 uuid.UUID)) *MockLoginService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginService_Delete_Call) Return(err error) *MockLoginService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginService_Delete_Call) RunAndReturn(run func(uUID uuid.UUID, uUID1 uuid.UUID) error) *MockLoginService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLoginService
func (_mock *MockLoginService) Get(uUID uuid.UUID, uUID1 uuid.UUID) (service.Login, error) {
	ret := _mock.Called(uUID, uUID1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (service.Login, error)); ok {
		return returnFunc(uUID, uUID1)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) service.Login); ok {
		r0 = returnFunc(uUID, uUID1)
	} else {
		r0 = ret.Get(0).(service.Login)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(uUID, uUID1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLoginService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - uUID1 uuid.UUID
func (_e *MockLoginService_Expecter) Get(uUID interface{}, uUID1 interface{}) *MockLoginService_Get_Call {
	return &MockLoginService_Get_Call{Call: _e.mock.On("Get", uUID, uUID1)}
}

func (_c *MockLoginService_Get_Call) Run(run func(uUID uuid.UUID, uUID1 uuid.UUID)) *MockLoginService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginService_Get_Call) Return(login service.Login, err error) *MockLoginService_Get_Call {
	_c.Call.Return(login, err)
	return _c
}

func (_c *MockLoginService_Get_Call) RunAndReturn(run func(uUID uuid.UUID, uUID1 uuid.UUID) (service.Login, error)) *MockLoginService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockLoginService
func (_mock *MockLoginService) List(uUID uuid.UUID, filters ...filter.Filter[service.Login]) ([]service.Login, error) {
	var tmpRet mock.Arguments
	if len(filters) > 0 {
		tmpRet = _mock.Called(uUID, filters)
	} else {
		tmpRet = _mock.Called(uUID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...filter.Filter[service.Login]) ([]service.Login, error)); ok {
		return returnFunc(uUID, filters...)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...filter.Filter[service.Login]) []service.Login); ok {
		r0 = returnFunc(uUID, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Login)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, ...filter.Filter[service.Login]) error); ok {
		r1 = returnFunc(uUID, filters...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLoginService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - filters ...filter.Filter[service.Login]
func (_e *MockLoginService_Expecter) List(uUID interface{}, filters ...interface{}) *MockLoginService_List_Call {
	return &MockLoginService_List_Call{Call: _e.mock.On("List",
		append([]interface{}{uUID}, filters...)...)}
}

func (_c *MockLoginService_List_Call) Run(run func(uUID uuid.UUID, filters ...filter.Filter[service.Login])) *MockLoginService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []filter.Filter[service.Login]
		var variadicArgs []filter.Filter[service.Login]
		if len(args) > 1 {
			variadicArgs = args[1].([]filter.Filter[service.Login])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLoginService_List_Call) Return(logins []service.Login, err error) *MockLoginService_List_Call {
	_c.Call.Return(logins, err)
	return _c
}

func (_c *MockLoginService_List_Call) RunAndReturn(run func(uUID uuid.UUID, filters ...filter.Filter[service.Login]) ([]service.Login, error)) *MockLoginService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoteService creates a new instance of MockNoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteService {
	mock := &MockNoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoteService is an autogenerated mock type for the NoteService type
type MockNoteService struct {
	mock.Mock
}

type MockNoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteService) EXPECT() *MockNoteService_Expecter {
	return &MockNoteService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNoteService
func (_mock *MockNoteService) Create(uUID uuid.UUID, note service.Note) error {
	ret := _mock.Called(uUID, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, service.Note) error); ok {
		r0 = returnFunc(uUID, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNoteService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - note service.Note
func (_e *MockNoteService_Expecter) Create(uUID interface{}, note interface{}) *MockNoteService_Create_Call {
	return &MockNoteService_Create_Call{Call: _e.mock.On("Create", uUID, note)}
}

func (_c *MockNoteService_Create_Call) Run(run func(uUID uuid.UUID, note service.Note)) *MockNoteService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 service.Note
		if args[1] != nil {
			arg1 = args[1].(service.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_Create_Call) Return(err error) *MockNoteService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteService_Create_Call) RunAndReturn(run func(uUID uuid.UUID, note service.Note) error) *MockNoteService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNoteService
func (_mock *MockNoteService) Delete(uUID uuid.UUID, uUID1 uuid.UUID) error {
	ret := _mock.Called(uUID, uUID1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(uUID, uUID1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoteService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNoteService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - uUID1 uuid.UUID
func (_e *MockNoteService_Expecter) Delete(uUID interface{}, uUID1 interface{}) *MockNoteService_Delete_Call {
	return &MockNoteService_Delete_Call{Call: _e.mock.On("Delete", uUID, uUID1)}
}

func (_c *MockNoteService_Delete_Call) Run(run func(uUID uuid.UUID, uUID1 uuid.UUID)) *MockNoteService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_Delete_Call) Return(err error) *MockNoteService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoteService_Delete_Call) RunAndReturn(run func(uUID uuid.UUID, uUID1 uuid.UUID) error) *MockNoteService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNoteService
func (_mock *MockNoteService) Get(uUID uuid.UUID, uUID1 uuid.UUID) (service.Note, error) {
	ret := _mock.Called(uUID, uUID1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (service.Note, error)); ok {
		return returnFunc(uUID, uUID1)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) service.Note); ok {
		r0 = returnFunc(uUID, uUID1)
	} else {
		r0 = ret.Get(0).(service.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(uUID, uUID1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNoteService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - uUID1 uuid.UUID
func (_e *MockNoteService_Expecter) Get(uUID interface{}, uUID1 interface{}) *MockNoteService_Get_Call {
	return &MockNoteService_Get_Call{Call: _e.mock.On("Get", uUID, uUID1)}
}

func (_c *MockNoteService_Get_Call) Run(run func(uUID uuid.UUID, uUID1 uuid.UUID)) *MockNoteService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoteService_Get_Call) Return(note service.Note, err error) *MockNoteService_Get_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNoteService_Get_Call) RunAndReturn(run func(uUID uuid.UUID, uUID1 uuid.UUID) (service.Note, error)) *MockNoteService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNoteService
func (_mock *MockNoteService) List(uUID uuid.UUID, filters ...filter.Filter[service.Note]) ([]service.Note, error) {
	var tmpRet mock.Arguments
	if len(filters) > 0 {
		tmpRet = _mock.Called(uUID, filters)
	} else {
		tmpRet = _mock.Called(uUID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...filter.Filter[service.Note]) ([]service.Note, error)); ok {
		return returnFunc(uUID, filters...)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...filter.Filter[service.Note]) []service.Note); ok {
		r0 = returnFunc(uUID, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, ...filter.Filter[service.Note]) error); ok {
		r1 = returnFunc(uUID, filters...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoteService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNoteService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - uUID uuid.UUID
//   - filters ...filter.Filter[service.Note]
func (_e *MockNoteService_Expecter) List(uUID interface{}, filters ...interface{}) *MockNoteService_List_Call {
	return &MockNoteService_List_Call{Call: _e.mock.On("List",
		append([]interface{}{uUID}, filters...)...)}
}

func (_c *MockNoteService_List_Call) Run(run func(uUID uuid.UUID, filters ...filter.Filter[service.Note])) *MockNoteService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []filter.Filter[service.Note]
		var variadicArgs []filter.Filter[service.Note]
		if len(args) > 1 {
			variadicArgs = args[1].([]filter.Filter[service.Note])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockNoteService_List_Call) Return(notes []service.Note, err error) *MockNoteService_List_Call {
	_c.Call.Return(notes, err)
	return _c
}

func (_c *MockNoteService_List_Call) RunAndReturn(run func(uUID uuid.UUID, filters ...filter.Filter[service.Note]) ([]service.Note, error)) *MockNoteService_List_Call {
	_c.Call.Return(run)
	return _c
}
