// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api_test

import (
	"github.com/davidsbond/passwords/internal/server/service"
	"github.com/davidsbond/passwords/internal/server/token"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatable creates a new instance of MockValidatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatable {
	mock := &MockValidatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatable is an autogenerated mock type for the Validatable type
type MockValidatable struct {
	mock.Mock
}

type MockValidatable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatable) EXPECT() *MockValidatable_Expecter {
	return &MockValidatable_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidatable
func (_mock *MockValidatable) Validate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidatable_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidatable_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *MockValidatable_Expecter) Validate() *MockValidatable_Validate_Call {
	return &MockValidatable_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *MockValidatable_Validate_Call) Run(run func()) *MockValidatable_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatable_Validate_Call) Return(err error) *MockValidatable_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidatable_Validate_Call) RunAndReturn(run func() error) *MockValidatable_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountService
func (_mock *MockAccountService) Create(account service.Account) ([]byte, error) {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(service.Account) ([]byte, error)); ok {
		return returnFunc(account)
	}
	if returnFunc, ok := ret.Get(0).(func(service.Account) []byte); ok {
		r0 = returnFunc(account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(service.Account) error); ok {
		r1 = returnFunc(account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account service.Account
func (_e *MockAccountService_Expecter) Create(account interface{}) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *MockAccountService_Create_Call) Run(run func(account service.Account)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 service.Account
		if args[0] != nil {
			arg0 = args[0].(service.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(bytes []byte, err error) *MockAccountService_Create_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(account service.Account) ([]byte, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(s string, s1 string) (token.Token, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (token.Token, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) token.Token); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(token.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockAuthService_Expecter) Login(s interface{}, s1 interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", s, s1)}
}

func (_c *MockAuthService_Login_Call) Run(run func(s string, s1 string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(token1 token.Token, err error) *MockAuthService_Login_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(s string, s1 string) (token.Token, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(uUID uuid.UUID) error {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockAuthService_Expecter) Logout(uUID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", uUID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(uUID uuid.UUID)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(uUID uuid.UUID) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) Create(password service.Password) error {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(service.Password) error); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - password service.Password
func (_e *MockPasswordService_Expecter) Create(password interface{}) *MockPasswordService_Create_Call {
	return &MockPasswordService_Create_Call{Call: _e.mock.On("Create", password)}
}

func (_c *MockPasswordService_Create_Call) Run(run func(password service.Password)) *MockPasswordService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 service.Password
		if args[0] != nil {
			arg0 = args[0].(service.Password)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordService_Create_Call) Return(err error) *MockPasswordService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordService_Create_Call) RunAndReturn(run func(password service.Password) error) *MockPasswordService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) List(uUID uuid.UUID) ([]service.Password, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.Password
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]service.Password, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []service.Password); ok {
		r0 = returnFunc(uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Password)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPasswordService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockPasswordService_Expecter) List(uUID interface{}) *MockPasswordService_List_Call {
	return &MockPasswordService_List_Call{Call: _e.mock.On("List", uUID)}
}

func (_c *MockPasswordService_List_Call) Run(run func(uUID uuid.UUID)) *MockPasswordService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordService_List_Call) Return(passwords []service.Password, err error) *MockPasswordService_List_Call {
	_c.Call.Return(passwords, err)
	return _c
}

func (_c *MockPasswordService_List_Call) RunAndReturn(run func(uUID uuid.UUID) ([]service.Password, error)) *MockPasswordService_List_Call {
	_c.Call.Return(run)
	return _c
}
