name: extension

on:
  push:
    paths:
      - 'extension/src/**'
      - 'extension/public/**'
      - 'extension/package.json'
      - 'extension/vite.config.ts'
      - '.github/workflows/extension.yml'
      - 'package.json'
    branches:
      - main
  pull_request:
    paths:
      - 'extension/src/**'
      - 'extension/public/**'
      - 'extension/package.json'
      - 'extension/vite.config.ts'
      - '.github/workflows/extension.yml'
      - 'package.json'

jobs:
  ci:
    uses: ./.github/workflows/node.yml
    secrets: inherit
    with:
      app: '@keeper/extension'
