name: node

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.html'
      - '**.json'
      - '**yarn.lock'
      - '.github/workflows/node.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.html'
      - '**.json'
      - '**yarn.lock'
      - '.github/workflows/node.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install node  
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: internal/server/ui/yarn.lock
          
      - name: Install dependencies
        working-directory: internal/server/ui
        run: yarn install
        
      - name: Format
        working-directory: internal/server/ui
        run: |
          yarn format
          git add .
          git diff --staged --exit-code

      - name: Build
        working-directory: internal/server/ui
        run: yarn build
