name: ui

on:
  push:
    paths:
      - 'internal/ui/**.js'
      - 'internal/ui/**.css'
      - 'internal/ui/package.json'
      - 'internal/ui/.prettierrc'
      - '.github/workflows/ui.yml'
      - 'package.json'
    branches:
      - main
  pull_request:
    paths:
      - 'internal/ui/**.js'
      - 'internal/ui/**.css'
      - 'internal/ui/package.json'
      - 'internal/ui/.prettierrc'
      - '.github/workflows/ui.yml'
      - 'package.json'

jobs:
  ci:
    uses: ./.github/workflows/node.yml
    secrets: inherit
    with:
      app: '@secrets/ui'
